apiVersion: v2
name: kube-chrony
description: Chrony Alpine NTP Server for Kubernetes
type: application
version: 0.1.0
keywords:
  - chrony
  - ntp
  - alpine
  - helm
  - kubernetes
sources:
  - https://hub.docker.com/r/cturra/ntp
home: https://github.com/GlennHD/kube-chrony
maintainers:
  - name: GlennHD
icon: https://cdn0.iconfinder.com/data/icons/phosphor-fill-vol-2/256/clock-clockwise-fill-512.png
appVersion: "latest"
