replicaCount: 2
strategyType: RollingUpdate
maxSurge: 1
maxUnavailable: 1

image:
  repository: "cturra/ntp"
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

serviceUDP:
  type: LoadBalancer
  port: 123
  externalTrafficPolicy: Local
  loadBalancerIP: "10.0.8.222"
  annotations:
    metallb.universe.tf/allow-shared-ip: kube-chrony

ntpServers: "time.nist.gov,us.pool.ntp.org"

ingress:
  enabled: false

probes:
  liveness:
    enabled: true
    periodSeconds: 10
    initialDelaySeconds: 30
    failureThreshold: 10
    timeoutSeconds: 15
  readiness:
    enabled: true
    periodSeconds: 10
    initialDelaySeconds: 30
    failureThreshold: 5
    timeoutSeconds: 15

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100

nodeSelector:
  ntp: ntp

tolerations: []
affinity: {}
extraEnvVars: {}
extraEnvVarsSecret: {}
