apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-chrony.fullname" . }}
  labels:
    {{- include "kube-chrony.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.strategyType }}
    {{- if eq .Values.strategyType "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "kube-chrony.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-chrony.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-chrony.serviceAccountName" . }}
      restartPolicy: Always
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: NTP_SERVERS
              value: {{ .Values.ntpServers }}
            {{- range $key, $value := .Values.extraEnvVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          securityContext:
            capabilities:
              add:
                - SYS_NICE
                - SYS_RESOURCE
                - SYS_TIME
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ntp
              containerPort: {{ .Values.serviceUDP.port }}
              protocol: UDP
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                - /usr/bin/probe.sh
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
                - /usr/bin/probe.sh
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/bin/probe.sh
              name: probe
              subPath: probe.sh
      volumes:
        - configMap:
            defaultMode: 511
            name: {{ template "kube-chrony.fullname" . }}-probe
          name: probe

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
